[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.18",
    "beautifulsoup4>=4.13.4",
    "discord-py>=2.5.2",
    "requests>=2.32.3",
    "trafilatura>=2.0.0",
]
